version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
    - 3000:3000
    networks:
      - react

networks:
  react:
    driver: bridge
